cacheSim: my_cacheSim.cpp
	g++ -g -o cacheSim my_cacheSim.cpp

oren_cacheSim: oren_cacheSim.cpp
	g++ -g -o oren_cacheSim oren_cacheSim.cpp

.PHONY: clean
clean:
	rm -f *.o
	rm -f cacheSim oren_cacheSim
